"""
self-host-fonts.py — Replace Google Fonts CDN with self-hosted woff2 files.

Eliminates two third-party DNS lookups per cold load (fonts.googleapis.com
+ fonts.gstatic.com) and gains 150-300ms FCP per the 2026-05-21 perf
audit. Also removes a tracking vector and lets us drop the gstatic.com /
googleapis.com entries from CSP connect-src.

Workflow:
  1. Hit Google Fonts CSS endpoint with a modern Chrome UA so it returns
     woff2 URLs.
  2. Parse out every fonts.gstatic.com woff2 URL it references.
  3. Download each woff2 to assets/fonts/<family>-<weight>[-italic].woff2
  4. Emit css/pfc-fonts.css with @font-face declarations pointing at the
     local files, using font-display: swap (matches Google's "&display=swap"
     query so visible-text behavior is identical).
  5. Print the HTML diff the user needs to apply (replace Google Fonts
     <link> tags with a single local <link rel="stylesheet" href="css/pfc-fonts.css">).

Run:  python scripts/self-host-fonts.py
"""
import os
import re
import sys
import urllib.request
import urllib.parse
from pathlib import Path

REPO = Path(__file__).resolve().parent.parent
FONTS_DIR = REPO / 'assets' / 'fonts'
CSS_OUT = REPO / 'css' / 'pfc-fonts.css'

# Modern Chrome UA so Google returns woff2 (older UAs get woff/ttf/eot).
UA = ('Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 '
      '(KHTML, like Gecko) Chrome/120.0.0.0 Safari/537.36')

# The exact Google Fonts CSS URL the site has been using in every HTML
# file's <link> tag. Captures every weight + italic combo the brand uses.
GFONTS_URL = (
    # NOTE: opsz (optical size) variable axis dropped — when present, Google
    # collapses all weights into a single variable woff2 and emits multiple
    # @font-face blocks all declaring `font-weight: 400` against the same
    # URL, which (a) confused our weight-specific filename derivation and
    # (b) made `font-weight: 600` requests in CSS not match. Without opsz,
    # Google returns one discrete woff2 per (weight, style) pair — exactly
    # what we want for self-hosting.
    'https://fonts.googleapis.com/css2'
    '?family=Fraunces:ital,wght@0,400;0,500;0,600;0,700;1,400;1,500;1,600'
    '&family=Inter+Tight:wght@300;400;500;600;700'
    '&family=JetBrains+Mono:wght@400;500;600'
    '&display=swap'
)


def fetch(url, decode='utf-8'):
    req = urllib.request.Request(url, headers={'User-Agent': UA})
    with urllib.request.urlopen(req, timeout=20) as r:
        data = r.read()
    return data.decode(decode) if decode else data


def main():
    FONTS_DIR.mkdir(parents=True, exist_ok=True)
    print(f'Fetching Google Fonts CSS...')
    css = fetch(GFONTS_URL)

    # The CSS is structured as a series of @font-face blocks, each with
    # font-family, font-style, font-weight, font-stretch (optional), and
    # src: url(...) format('woff2'). Parse with a tolerant regex.
    face_re = re.compile(
        r'@font-face\s*\{([^}]+)\}',
        re.DOTALL
    )
    prop_re = lambda name: re.compile(rf'{name}\s*:\s*([^;]+);')
    url_re = re.compile(r"url\(([^)]+\.woff2)\)")

    out_css_lines = [
        '/* pfc-fonts.css — self-hosted woff2 declarations.',
        ' * Generated by scripts/self-host-fonts.py. Do not edit by hand;',
        ' * re-run the script after changing the weight list in the source.',
        ' *',
        ' * Replaces the Google Fonts CDN <link> tags that used to live in',
        ' * every HTML file. font-display: swap is preserved so visible-text',
        ' * timing matches the prior CDN behavior.',
        ' */',
        '',
    ]

    # Strategy:
    # - Google emits a @font-face per (weight, style, unicode-subset). Many
    #   blocks may share the SAME variable woff2 URL (one variable file
    #   covers all weights via the wght axis).
    # - We want one @font-face per (weight, style) pointing to a local
    #   copy of the file. Unicode-range is collapsed to "all" so the
    #   browser matches regardless of which subset's chars are on the page.
    # - We dedup downloads by URL (one local file per unique URL) but
    #   emit multiple @font-face blocks that all reference the same local
    #   file when Google's response shared one URL across weights.
    downloaded = 0
    skipped_cached = 0
    emitted_pairs = set()   # (family, weight, style)
    url_to_local = {}       # url -> local_name

    for block_match in face_re.finditer(css):
        block = block_match.group(1)

        family_m = prop_re('font-family').search(block)
        style_m  = prop_re('font-style').search(block)
        weight_m = prop_re('font-weight').search(block)
        url_m    = url_re.search(block)

        if not (family_m and url_m):
            continue

        family = family_m.group(1).strip().strip("'\"")
        style  = (style_m.group(1).strip() if style_m else 'normal')
        weight = (weight_m.group(1).strip() if weight_m else '400')
        url    = url_m.group(1).strip()

        pair_key = (family, weight, style)
        if pair_key in emitted_pairs:
            continue
        emitted_pairs.add(pair_key)

        # Ensure the file is on disk (download once per unique URL).
        if url in url_to_local:
            local_name = url_to_local[url]
        else:
            slug = family.lower().replace(' ', '-')
            italic_suffix = '-italic' if style == 'italic' else ''
            local_name = f'{slug}-{weight}{italic_suffix}.woff2'
            local_path = FONTS_DIR / local_name
            if local_path.exists() and local_path.stat().st_size > 1000:
                skipped_cached += 1
            else:
                print(f'  downloading {local_name} ({url[-60:]})')
                try:
                    data = fetch(url, decode=None)
                    with open(local_path, 'wb') as fh:
                        fh.write(data)
                    downloaded += 1
                except Exception as e:
                    print(f'    FAILED: {e}', file=sys.stderr)
                    continue
            url_to_local[url] = local_name

        # Emit @font-face. unicode-range omitted -> browser uses this for
        # any character, which is what we want for a self-hosted setup
        # where subset-splitting buys us nothing (no CDN edge benefit).
        out_css_lines.append(f"@font-face {{")
        out_css_lines.append(f"  font-family: '{family}';")
        out_css_lines.append(f"  font-style: {style};")
        out_css_lines.append(f"  font-weight: {weight};")
        out_css_lines.append(f"  font-display: swap;")
        out_css_lines.append(f"  src: url('/assets/fonts/{local_name}') format('woff2');")
        out_css_lines.append(f"}}")
        out_css_lines.append("")

    CSS_OUT.write_text('\n'.join(out_css_lines), encoding='utf-8')

    print()
    print(f'Downloaded:    {downloaded} new files')
    print(f'Skipped cached: {skipped_cached}')
    print(f'Wrote:         {CSS_OUT.relative_to(REPO)} ({len(out_css_lines)} lines)')
    print(f'Total fonts dir size: {sum(p.stat().st_size for p in FONTS_DIR.iterdir()) // 1024} KB')


if __name__ == '__main__':
    main()
